version: '3.4'

services:
  postgres:
    image: postgres:14.10
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:7.2.3
    expose:
      - 6379
    volumes:
      - redis:/var/lib/redis/data

  rails:
    command: ./bin/rails server -p 3000 -b 0.0.0.0
    build: .
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/rails:cached
      - bundle:/bundle
    tty: true
    stdin_open: true
    environment:
      - GEOLOCATION_API_DATABASE_URL="postgres://postgres:password@postgres/geolocation_api_production"

volumes:
  bundle:
  postgres:
  redis:
